# Cấu hình Spring Boot: Kết nối Supabase PostgreSQL, đồng bộ migration qua Flyway và kiểm soát thực thể bằng JPA.
spring:
  application:
    name: bfms-backend
    # 1. Cấu hình kết nối tới Supabase (PostgreSQL)
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.beposyakzytatojdkuvm
    password: "SDtb@3po3Pi"
    driver-class-name: org.postgresql.Driver

  # 2. Cấu hình Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-on-migrate: true

  # 3. Cấu hình Spring Data JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect